version: 2.1

setup: true

parameters:
  dispatch-schema-to-client:
    type: boolean
    default: false

orbs: 
  path-filtering: circleci/path-filtering@0.1.3

workflows:
  generate-config:
   jobs:
    - path-filtering/filter:
        base-revision: develop
        mapping: |
          graph/schema.graphqls dispatch-schema-to-client true