version: 2.1

jobs:
  dispatch-schema-to-client:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: "uname"
          command: "uname -s"

workflows:
  dispatch-schema-to-client:
    jobs:
      - say-hello