version: 2.1

jobs:
  dispatch-schema-to-client:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - run:
          command: go run server.go
          background: true
      - run: sleep 5
      - run:
          name: "install rover"
          command: |
            curl -sSL https://rover.apollo.dev/nix/latest | sh
            echo 'export PATH=$HOME/.rover/bin:$PATH' >> $BASH_ENV
      - run: rover graph introspect http://localhost:8080/query --output json >> schema.json
      - add_ssh_keys:
          fingerprints:
            - "2b:fa:60:7f:a3:2c:d1:c9:9b:98:2d:0e:f6:81:12:a4"
      - run: git clone https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/tokizuoh/contrail2
      - run: cd contrail2
      - run: git log -5

workflows:
  say-hello-workflow:
    jobs:
      - dispatch-schema-to-client