version: 2.1

jobs:
  dispatch-schema-to-client:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - run:
          command: go run server.go
          background: true
      - run: sleep 10
      - run:
          name: "install rover"
          command: |
            curl -sSL https://rover.apollo.dev/nix/latest | sh
            echo 'export PATH=$HOME/.rover/bin:$PATH' >> $BASH_ENV
      - run: rover graph introspect http://localhost:8080/query --output json >> schema.json
      - run: cat schema.json

workflows:
  say-hello-workflow:
    jobs:
      - dispatch-schema-to-client