version: 2.1

parameters:
  dispatch-schema-to-client:
    type: boolean
    default: false

orbs: 
  node: circleci/node@5.0.2

jobs:
  dispatch-schema-to-client:
    docker:
      - image: cimg/go:1.18.4
    steps:
      - checkout
      - run:
          command: go run server.go
          background: true
      - node/install:
          node-version: 14.20.0
      - run: npm install apollo
      - run: npx apollo service:download --endpoint http://localhost:8080/query
      - add_ssh_keys:
          fingerprints:
            - "2b:fa:60:7f:a3:2c:d1:c9:9b:98:2d:0e:f6:81:12:a4"
      - run:
          name: "commit schema.json to client repository"
          command: |
            git clone https://${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/tokizuoh/contrail
            mv schema.json contrail/contrail/contrail/generated/schema.json
            cd contrail
            git config user.email ${GITHUB_EMAIL}
            git config user.name "tokizuoh+circleci"
          
            git checkout -b test-circleci
            git add contrail/contrail/contrail/generated/schema.json
            git commit -m '[CircleCI] update schema.json' || true
            git push origin HEAD:develop

workflows:
  dispatch-schema-to-client:
    jobs:
      - dispatch-schema-to-client
    when: << pipeline.parameters.dispatch-schema-to-client >>