// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewWorkout struct {
	Distance float64 `json:"distance"`
	Duration float64 `json:"duration"`
}

type Workout struct {
	Distance float64 `json:"distance"`
	Duration float64 `json:"duration"`
}
