name: Dispatch schema.json to tokizuoh/contrail2
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - run: go run server.go &
      - run: sleep 10
      - run: |
          npm install -D apollo
          apollo schema:download --endpoint=http://localhost:8080/query schema.json
      - run: ls

  # goサーバー生成
  # CLIダウンロード
  # スキーマDL
  # tokizuoh/contrail2にcommitする