name: Dispatch schema.json to tokizuoh/contrail2
on: [push]
jobs:
  go-run-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - run: go run server
  curl:
    needs: go-run-server
    runs-on: ubuntu-latest
    steps:
      - curl localhost:8080

  # goサーバー生成
  # CLIダウンロード
  # スキーマDL
  # tokizuoh/contrail2にcommitする