name: Dispatch schema.json to tokizuoh/contrail2
on: [push]
jobs:
  setup:
    runs-on: macos-12
    steps:
      - name: check out
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - run: go run server.go &
      - run: sleep 10
      - run: curl -sSL https://rover.apollo.dev/nix/latest | sh
      - run: sleep 5
      - run: rover graph introspect http://localhost:8080/query --output json >> schema.json
      - run: ls

  # goサーバー生成
  # CLIダウンロード
  # スキーマDL
  # tokizuoh/contrail2にcommitする